# Generated by Django 5.0.14 on 2026-08-17 06:03

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shablon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=100)),
                (
                    "kod",
                    models.SlugField(
                        help_text="Shablon fayl nomi, masalan: registon", unique=True
                    ),
                ),
                (
                    "rasm",
                    models.ImageField(blank=True, null=True, upload_to="shablonlar/"),
                ),
                ("narx", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "ommaviy",
                    models.BooleanField(
                        default=True,
                        help_text="False bo'lsa — individual/maxfiy shablon, faqat admin biriktira oladi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shablon",
                "verbose_name_plural": "Shablonlar",
                "ordering": ["nomi"],
            },
        ),
        migrations.CreateModel(
            name="Taklifnoma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kuyov", models.CharField(max_length=100)),
                ("kelin", models.CharField(max_length=100)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Ochiq link uchun, masalan: sardor-malika",
                        unique=True,
                    ),
                ),
                ("sana", models.DateTimeField(help_text="To'y sanasi va vaqti")),
                ("toyxona", models.CharField(blank=True, max_length=200)),
                ("manzil", models.CharField(blank=True, max_length=300)),
                ("xarita_link", models.URLField(blank=True)),
                ("musiqa", models.FileField(blank=True, upload_to="musiqa/")),
                (
                    "matn",
                    models.TextField(
                        blank=True, help_text="Qo'shimcha tabrik/taklif matni"
                    ),
                ),
                ("faol", models.BooleanField(default=True)),
                ("korishlar", models.PositiveIntegerField(default=0)),
                (
                    "statistika_token",
                    models.CharField(
                        default=secrets.token_hex,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "sovga_karta",
                    models.CharField(
                        blank=True,
                        help_text="Pul sovg'a uchun karta raqami",
                        max_length=50,
                    ),
                ),
                (
                    "tolangan",
                    models.BooleanField(
                        default=True,
                        help_text="Self-service oqimi uchun: mijoz to'laguncha False bo'ladi",
                    ),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "shablon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="taklifnomalar",
                        to="taklif.shablon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taklifnoma",
                "verbose_name_plural": "Taklifnomalar",
                "ordering": ["-yaratilgan"],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism", models.CharField(max_length=100)),
                ("keladi", models.BooleanField()),
                ("mehmonlar_soni", models.PositiveSmallIntegerField(default=1)),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "taklifnoma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="javoblar",
                        to="taklif.taklifnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSVP javobi",
                "verbose_name_plural": "RSVP javoblari",
                "ordering": ["-yaratilgan"],
            },
        ),
    ]
