# Generated by Django 5.0.14 on 2026-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="izoh",
            field=models.CharField(
                blank=True,
                help_text="Ixtiyoriy izoh (masalan: allergiya, maxsus talab)",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="taklifnoma",
            name="kiyim_kodi",
            field=models.CharField(
                blank=True, help_text="Masalan: rasmiy, yorug' ranglar", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="taklifnoma",
            name="telegram_link",
            field=models.URLField(
                blank=True, help_text="Mehmonlar uchun Telegram guruh/kanal havolasi"
            ),
        ),
    ]
