# Generated by Django 5.0.14 on 2026-08-17 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0002_rsvp_izoh_taklifnoma_kiyim_kodi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaklifnomaRasm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rasm", models.ImageField(upload_to="taklifnoma_rasmlar/")),
                ("tartib", models.PositiveSmallIntegerField(default=0)),
                (
                    "taklifnoma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rasmlar",
                        to="taklif.taklifnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taklifnoma rasmi",
                "verbose_name_plural": "Taklifnoma rasmlari",
                "ordering": ["tartib", "id"],
            },
        ),
    ]
