# Generated by Django 5.0.14 on 2026-08-17 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0004_boshlangich_shablonlar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mehmon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ism",
                    models.CharField(
                        help_text="Masalan: Aziz oila, Malika", max_length=100
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Bo'sh qoldirsangiz, ismdan avtomatik yasaladi",
                        max_length=60,
                    ),
                ),
                ("korilgan", models.BooleanField(default=False, editable=False)),
                (
                    "korilgan_vaqt",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("yaratilgan", models.DateTimeField(auto_now_add=True)),
                (
                    "taklifnoma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mehmonlar",
                        to="taklif.taklifnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mehmon (shaxsiy link)",
                "verbose_name_plural": "Mehmonlar (shaxsiy linklar)",
                "ordering": ["ism"],
            },
        ),
        migrations.AddField(
            model_name="rsvp",
            name="mehmon",
            field=models.ForeignKey(
                blank=True,
                help_text="Agar mehmon shaxsiy link orqali kirgan bo'lsa, avtomatik bog'lanadi",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="javoblar",
                to="taklif.mehmon",
            ),
        ),
        migrations.AddConstraint(
            model_name="mehmon",
            constraint=models.UniqueConstraint(
                fields=("taklifnoma", "slug"), name="taklif_mehmon_slug_unique"
            ),
        ),
    ]
