# Generated by Django 5.0.14 on 2026-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0008_qoshimcha_shablonlar"),
    ]

    operations = [
        migrations.AddField(
            model_name="musiqavariant",
            name="til",
            field=models.CharField(
                choices=[
                    ("uz", "O'zbekcha"),
                    ("ru", "Русский"),
                    ("en", "English"),
                    ("tg", "Тоҷикӣ"),
                    ("kk", "Қазақша"),
                    ("ky", "Кыргызча"),
                    ("tk", "Türkmençe"),
                    ("kaa", "Qaraqalpaqsha"),
                ],
                default="uz",
                help_text="Sayt shu tilda ko'rilayotganda fon musiqasi sifatida yangraydi. Bitta tilda bir nechta variant bo'lsa, birinchisi olinadi.",
                max_length=10,
            ),
        ),
    ]
