# Generated by Django 5.0.14 on 2026-08-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0009_musiqavariant_til"),
    ]

    operations = [
        migrations.AddField(
            model_name="shablon",
            name="turkum",
            field=models.CharField(
                choices=[
                    ("zamonaviy", "Zamonaviy"),
                    ("milliy", "Milliy"),
                    ("bolalar", "Bolalar"),
                ],
                default="zamonaviy",
                help_text="Shablon tanlash sahifasida shu turkum ostida ko'rinadi",
                max_length=20,
            ),
        ),
    ]
