# Generated by Django 5.0.14 on 2026-08-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0012_hashamatli_zamonaviy_shablonlar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taklifnoma",
            name="ism_1",
            field=models.CharField(
                help_text="Masalan: kuyov, tug'ilgan kun egasi", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="taklifnoma",
            name="ism_2",
            field=models.CharField(
                blank=True,
                help_text="Ikkinchi ism (masalan: kelin). Kerak bo'lmasa bo'sh qoldiring",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="taklifnoma",
            name="marosim_turi",
            field=models.CharField(
                choices=[
                    ("toy", "Nikoh to'yi"),
                    ("qizlar_bazmi", "Qiz uzatish"),
                    ("sunnat_toy", "Sunnat to'yi"),
                    ("beshik_toy", "Beshik to'yi"),
                    ("nahor_oshi", "Nahor oshi"),
                    ("yubiley", "Yubiley"),
                    ("tugilgan_kun", "Tug'ilgan kun"),
                    ("boshqa", "Boshqa"),
                ],
                default="toy",
                max_length=20,
            ),
        ),
    ]
