# Generated by Django 5.0.14 on 2026-08-25 09:57

import datetime

from django.db import migrations, models
from django.utils import timezone

# Shablon tanlash sahifasida "Namuna ko'rish" tugmasi uchun har bir tanlangan
# shablonga bittadan ko'rgazma taklifnoma va unga mos rasm(lar). Rasmlarning
# o'zi (jpg fayllar) media/taklifnoma_rasmlar/ ichida alohida yetkaziladi —
# bu yerda faqat DB yozuvi yaratiladi, fayl nomlari shu papkadagilarga mos.
NAMUNALAR = [
    {"shablon_kod": "suzani", "rasmlar": ["namuna-suzani-1.jpg", "namuna-suzani-2.jpg"]},
    {"shablon_kod": "ravoq", "rasmlar": ["namuna-ravoq-1.jpg"]},
    {"shablon_kod": "anor", "rasmlar": ["namuna-anor-1.jpg"]},
    {"shablon_kod": "qandil", "rasmlar": ["namuna-qandil-1.jpg", "namuna-qandil-2.jpg"]},
    {"shablon_kod": "zarhal", "rasmlar": ["namuna-zarhal-1.jpg", "namuna-zarhal-2.jpg"]},
    {"shablon_kod": "tojik", "rasmlar": ["namuna-tojik-1.jpg", "namuna-tojik-2.jpg"]},
    {"shablon_kod": "kristall", "rasmlar": ["namuna-kristall-1.jpg", "namuna-kristall-2.jpg"]},
    {"shablon_kod": "sadaf", "rasmlar": ["namuna-sadaf-1.jpg", "namuna-sadaf-2.jpg"]},
    {"shablon_kod": "chinni", "rasmlar": ["namuna-chinni-1.jpg", "namuna-chinni-2.jpg"]},
]


def namunalarni_yaratish(apps, schema_editor):
    Shablon = apps.get_model("taklif", "Shablon")
    Taklifnoma = apps.get_model("taklif", "Taklifnoma")
    TaklifnomaRasm = apps.get_model("taklif", "TaklifnomaRasm")

    sana = timezone.now() + datetime.timedelta(days=270)

    for maydon in NAMUNALAR:
        shablon = Shablon.objects.filter(kod=maydon["shablon_kod"]).first()
        if not shablon:
            continue
        slug = f"namuna-{maydon['shablon_kod']}"
        taklifnoma, _ = Taklifnoma.objects.update_or_create(
            slug=slug,
            defaults=dict(
                marosim_turi="toy",
                ism_1="Aziz",
                ism_2="Malika",
                shablon=shablon,
                sana=sana,
                toyxona="Bog'i Rayhon to'yxonasi",
                manzil="Toshkent shahri, Chilonzor tumani",
                kiyim_kodi="Rasmiy / to'q ranglar",
                matn="Sizni baxtimizga chin dildan sherik bo'lishga taklif qilamiz!",
                faol=True,
                tolangan=True,
                namuna=True,
            ),
        )
        taklifnoma.rasmlar.all().delete()
        for tartib, fayl_nomi in enumerate(maydon["rasmlar"]):
            TaklifnomaRasm.objects.create(
                taklifnoma=taklifnoma,
                rasm=f"taklifnoma_rasmlar/{fayl_nomi}",
                tartib=tartib,
            )


def namunalarni_olib_tashlash(apps, schema_editor):
    Taklifnoma = apps.get_model("taklif", "Taklifnoma")
    Taklifnoma.objects.filter(namuna=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0015_eng_oddiy_shablonlarni_olib_tashlash"),
    ]

    operations = [
        migrations.AddField(
            model_name="taklifnoma",
            name="namuna",
            field=models.BooleanField(
                default=False,
                help_text="Bu — mijozlar ma'lumoti emas, sayt uchun ko'rgazma taklifnoma. Shablon tanlash sahifasidagi 'Namuna ko'rish' tugmasi shu taklifnomaga olib boradi va bosh sahifadagi haqiqiy mijozlar ro'yxatida ko'rinmaydi.",
            ),
        ),
        migrations.RunPython(namunalarni_yaratish, namunalarni_olib_tashlash),
    ]
