# Generated by Django 5.0.14 on 2026-08-25 10:21

from django.db import migrations, models

# "Namuna ko'rish" (tayyor ko'rgazma taklifnoma) g'oyasi noto'g'ri tushunilgan
# edi — mijozga tayyor birovning taklifnomasini ko'rsatish qiziqishni
# o'ldiradi. Shu sababli 0016'da yaratilgan namuna taklifnomalar bu yerda
# o'chiriladi, ular o'rniga rasm/musiqaga o'xshab, YARATISH formasining
# o'zida "tayyor namunalardan tanlash" imkoniyati (NamunaRasm) qo'shiladi.
NAMUNA_RASMLAR = [f"namuna-rasm-{i:02d}.jpg" for i in range(1, 17)]

# Shablon tanlash sahifasidagi mini-kartalarni tekis rang o'rniga nafis
# fotosurat orqasiga yashirish uchun (Shablon.rasm maydoni allaqachon bor,
# shunchaki bo'sh edi).
SHABLON_FONLARI = {
    "suzani": "suzani-namuna.jpg",
    "ravoq": "ravoq-namuna.jpg",
    "anor": "anor-namuna.jpg",
    "qandil": "qandil-namuna.jpg",
    "zarhal": "zarhal-namuna.jpg",
    "tojik": "tojik-namuna.jpg",
    "kristall": "kristall-namuna.jpg",
    "sadaf": "sadaf-namuna.jpg",
    "chinni": "chinni-namuna.jpg",
}


def eski_namunalarni_olib_tashlash(apps, schema_editor):
    Taklifnoma = apps.get_model("taklif", "Taklifnoma")
    Taklifnoma.objects.filter(namuna=True).delete()


def eski_namunalarni_qaytarish(apps, schema_editor):
    # Taklifnoma yozuvlarini tiklab bo'lmaydi — ataylab o'chirish.
    pass


def kutubxonani_toldirish(apps, schema_editor):
    NamunaRasm = apps.get_model("taklif", "NamunaRasm")
    Shablon = apps.get_model("taklif", "Shablon")

    for tartib, fayl_nomi in enumerate(NAMUNA_RASMLAR):
        NamunaRasm.objects.get_or_create(
            rasm=f"namuna_rasmlar/{fayl_nomi}",
            defaults={"tartib": tartib},
        )

    for kod, fayl_nomi in SHABLON_FONLARI.items():
        Shablon.objects.filter(kod=kod).update(rasm=f"shablonlar/{fayl_nomi}")


def kutubxonani_boshatish(apps, schema_editor):
    NamunaRasm = apps.get_model("taklif", "NamunaRasm")
    Shablon = apps.get_model("taklif", "Shablon")
    NamunaRasm.objects.all().delete()
    Shablon.objects.filter(kod__in=list(SHABLON_FONLARI)).update(rasm="")


class Migration(migrations.Migration):

    # DIQQAT: bu migratsiya bitta jadvalda (taklif_taklifnoma) avval
    # ma'lumot o'chirish (RunPython) va keyin ustun o'chirish (RemoveField)
    # ni birga qiladi. SQLite'da bu muammo bermaydi, lekin PostgreSQL bitta
    # tranzaksiya ichida shu ikkalasini ketma-ket qilishga yo'l qo'ymaydi
    # ("cannot ALTER TABLE because it has pending trigger events" xatosi) —
    # buni haqiqiy Postgres bazasida sinab ko'rganda aniqladim. Shu sababli
    # bu migratsiya BITTA tranzaksiyaga o'ralmasligi kerak.
    atomic = False

    dependencies = [
        ("taklif", "0016_namuna_taklifnomalar"),
    ]

    operations = [
        migrations.RunPython(
            eski_namunalarni_olib_tashlash, eski_namunalarni_qaytarish
        ),
        migrations.CreateModel(
            name="NamunaRasm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomi",
                    models.CharField(
                        blank=True,
                        help_text="Faqat admin uchun ichki nom (ixtiyoriy)",
                        max_length=100,
                    ),
                ),
                ("rasm", models.ImageField(upload_to="namuna_rasmlar/")),
                ("tartib", models.PositiveSmallIntegerField(default=0)),
                ("faol", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Namuna rasm",
                "verbose_name_plural": "Namuna rasmlar",
                "ordering": ["tartib", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="taklifnoma",
            name="namuna",
        ),
        migrations.RunPython(kutubxonani_toldirish, kutubxonani_boshatish),
    ]
