# Generated by Django 5.0.14 on 2026-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0017_namuna_rasmlar_kutubxonasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaytSozlamalari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_telegram",
                    models.CharField(
                        blank=True,
                        help_text="Mijoz \"Yoqdi, to'lov qilmoqchiman\" tugmasini bosganda yo'naltiriladigan Telegram username, @ belgisi bilan (masalan: @username). Bo'sh qoldirilsa, serverdagi standart qiymat (SAYT_ADMIN_TELEGRAM) ishlatiladi.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sayt sozlamalari",
                "verbose_name_plural": "Sayt sozlamalari",
            },
        ),
    ]
