# Generated by Django 5.0.14 on 2026-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0019_eski_rsvp_takrorlarini_tozalash"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rsvp",
            constraint=models.UniqueConstraint(
                fields=("taklifnoma", "mehmon"), name="rsvp_taklifnoma_mehmon_bir_marta"
            ),
        ),
    ]
