# Generated by Django 5.0.14 on 2026-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0020_rsvp_taklifnoma_mehmon_bir_marta"),
    ]

    operations = [
        migrations.AddField(
            model_name="taklifnoma",
            name="ochirilgan_vaqt",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Mijoz o'zi o'chirgan FAOLLASHTIRILGAN (to'langan) taklifnoma shu vaqtda \"chiqindilar\"ga o'tkazilgan — faol=False qilingan, lekin ma'lumotlari (RSVP, rasmlar) darhol o'chirilmagan, CHIQINDI_SAQLASH_KUNLARI kun ichida admin panelidan tiklash mumkin. Bo'sh bo'lsa — hech qachon o'chirilmagan.",
                null=True,
            ),
        ),
    ]
