# Generated by Django 5.0.14 on 2026-08-30 07:45

import django.core.validators
import taklif.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0021_taklifnoma_ochirilgan_vaqt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taklifnoma",
            name="musiqa",
            field=models.FileField(
                blank=True,
                help_text="O'zingiz yuklamoqchi bo'lsangiz (mp3/wav/ogg/m4a/aac, 15 MB gacha)",
                upload_to="musiqa/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp3", "wav", "ogg", "m4a", "aac"]
                    ),
                    taklif.validators.FaylHajmiValidator(15),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="taklifnomarasm",
            name="rasm",
            field=models.ImageField(
                upload_to="taklifnoma_rasmlar/",
                validators=[taklif.validators.FaylHajmiValidator(8)],
            ),
        ),
    ]
