# Generated by Django 5.0.14 on 2026-08-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0022_alter_taklifnoma_musiqa_alter_taklifnomarasm_rasm"),
    ]

    operations = [
        migrations.AddField(
            model_name="taklifnoma",
            name="ommaviy_korsatishga_rozi",
            field=models.BooleanField(
                default=False,
                help_text="Yoqilsa, taklifnoma (ism, marosim turi, sana) sayt bosh sahifasidagi \"So'nggi taklifnomalar\" bo'limida boshqa mijozlarga namuna sifatida ko'rsatilishi mumkin. Standart holatda O'CHIQ — faqat mijoz o'zi aniq rozilik bildirsa yoqiladi.",
                verbose_name="Bosh sahifada namuna sifatida ko'rsatishga rozilik",
            ),
        ),
    ]
