# Generated by Django 5.0.14 on 2026-08-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0023_taklifnoma_ommaviy_korsatishga_rozi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shablon",
            name="narx",
            field=models.DecimalField(
                decimal_places=0,
                help_text="So'mda, masalan: 180000. Shablon tanlash va bosh sahifadagi narx shu yerdan olinadi.",
                max_digits=10,
            ),
        ),
    ]
