# Generated by Django 5.0.14 on 2026-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0024_alter_shablon_narx"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="tilak",
            field=models.CharField(
                blank=True,
                help_text="Ixtiyoriy tabrik/tilak — yozilsa, taklifnoma sahifasida BARCHAGA ochiq ko'rinadi.",
                max_length=500,
            ),
        ),
    ]
