# Generated by Django 5.0.14 on 2026-08-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0025_rsvp_tilak"),
    ]

    operations = [
        migrations.AddField(
            model_name="rsvp",
            name="tilak_tasdiqlangan",
            field=models.BooleanField(
                default=False,
                help_text="Yoqilgan bo'lsa — tilak taklifnoma sahifasida hammaga ochiq. O'chiq bo'lsa — faqat mezbonga (statistika sahifasida) ko'rinadi.",
            ),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="tilak",
            field=models.CharField(
                blank=True,
                help_text="Ixtiyoriy tabrik/tilak — avval faqat mezbonga ko'rinadi, mezbon tasdiqlagach taklifnoma sahifasida BARCHAGA ochiq bo'ladi.",
                max_length=500,
            ),
        ),
    ]
