# Generated by Django 5.0.14 on 2026-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0026_rsvp_tilak_tasdiqlangan_alter_rsvp_tilak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mehmon",
            name="ism",
            field=models.CharField(
                help_text="Masalan: Jasur Rahimov, Aliyevlar oilasi", max_length=100
            ),
        ),
    ]
