# Generated by Django 5.0.14 on 2026-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0027_alter_mehmon_ism"),
    ]

    operations = [
        migrations.AddField(
            model_name="taklifnoma",
            name="boshqa_tadbir_nomi",
            field=models.CharField(
                blank=True,
                help_text='Marosim turi "Boshqa" bo\'lganda, tadbir nomini shu yerga yozing',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="taklifnoma",
            name="ism_3",
            field=models.CharField(
                blank=True,
                help_text="Uchinchi ism — faqat sunnat to'yida, agar bir nechta to'ybola bo'lsa. Kerak bo'lmasa bo'sh qoldiring",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="taklifnoma",
            name="matn",
            field=models.TextField(
                blank=True,
                help_text="Mehmonlarga atalgan so'z — taklifnomada ularga to'g'ridan-to'g'ri ko'rsatiladi",
            ),
        ),
    ]
