# Generated by Django 5.0.14 on 2026-09-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taklif', '0029_shablon_millat_shablon_marosim_turi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taklifnoma',
            name='ism_3',
            field=models.CharField(blank=True, help_text="Uchinchi ism — faqat xatna to'yida, agar bir nechta to'ybola bo'lsa. Kerak bo'lmasa bo'sh qoldiring", max_length=100),
        ),
    ]
