# Generated by Django 5.0.14 on 2026-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0032_marosim_turlari_kop_tanlovga_otish"),
    ]

    operations = [
        migrations.AddField(
            model_name="taklifnoma",
            name="dastur",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Kun tartibi — [{'vaqt': '18:00', 'nom': 'Mehmonlarni qarshi olish', 'izoh': ''}] ko'rinishidagi ro'yxat. Bo'sh bo'lsa, taklifnomada bu bo'lim umuman ko'rsatilmaydi.",
            ),
        ),
        migrations.AddField(
            model_name="taklifnoma",
            name="imzo",
            field=models.CharField(
                blank=True,
                help_text="Taklifnoma kim nomidan kelayotgani — masalan “Aliyevlar oilasi”. Bo'sh qoldirilsa, marosim egalarining ismlari ishlatiladi.",
                max_length=120,
            ),
        ),
    ]
