# Generated by Django 5.0.14 on 2026-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0033_taklifnoma_dastur_taklifnoma_imzo"),
    ]

    operations = [
        migrations.AddField(
            model_name="saytsozlamalari",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="Instagram username — @ bilan ham, to'liq havola bilan ham yozish mumkin (masalan: oqqushlar.uz). Bo'sh qoldirilsa ko'rsatilmaydi.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="saytsozlamalari",
            name="telefon",
            field=models.CharField(
                blank=True,
                help_text="Bog'lanish uchun telefon raqami, masalan: +998 90 123 45 67. Bo'sh qoldirilsa, saytda telefon umuman ko'rsatilmaydi.",
                max_length=40,
            ),
        ),
    ]
