# Generated by Django 5.0.14 on 2026-09-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0036_marosim_dizaynlarini_katalogga_qoshish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiqavariant",
            name="marosim_turlari_raw",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Qaysi marosim turlariga mos — bir nechtasini belgilash mumkin. Hech biri belgilanmasa, cheklov yo'q deb hisoblanadi va BARCHA marosim turlarida ko'rinadi.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="namunarasm",
            name="marosim_turlari_raw",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Qaysi marosim turlariga mos — bir nechtasini belgilash mumkin. Hech biri belgilanmasa, cheklov yo'q deb hisoblanadi va BARCHA marosim turlarida ko'rinadi.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="shablon",
            name="marosim_turlari_raw",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Qaysi marosim turlariga mos — bir nechtasini belgilash mumkin. Hech biri belgilanmasa, cheklov yo'q deb hisoblanadi va BARCHA marosim turlarida ko'rinadi.",
                max_length=200,
            ),
        ),
    ]
