# Generated by Django 5.0.14 on 2026-09-09 06:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0037_marosim_turlari_izohini_toldirish"),
    ]

    operations = [
        migrations.CreateModel(
            name="Naqsh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomi",
                    models.CharField(help_text="Masalan: So'zana guli", max_length=100),
                ),
                (
                    "kalit",
                    models.SlugField(
                        help_text="Fayl nomi (kengaytmasiz). Fayl shu yerda turishi shart: taklif/static/taklif/naqshlar/<kalit>.webp",
                        unique=True,
                    ),
                ),
                (
                    "millat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ozbek", "O'zbek"),
                            ("qozoq", "Qozoq"),
                            ("qirgiz", "Qirg'iz"),
                            ("tojik", "Tojik"),
                            ("turkman", "Turkman"),
                            ("qoraqalpoq", "Qoraqalpoq"),
                            ("rus", "Rus"),
                        ],
                        default="",
                        help_text="Mijozga naqsh tanlashda shu millat ostida ko'rsatiladi. Bo'sh qoldirilsa — har qanday millatda ko'rinadi.",
                        max_length=20,
                    ),
                ),
                (
                    "joylashuv",
                    models.CharField(
                        choices=[
                            ("tepa", "Tepada, takrorlanmaydi"),
                            ("maydon", "Butun sahifa bo'ylab, takrorlanadi"),
                        ],
                        default="tepa",
                        help_text='"Tepada" — naqsh bir marta sahifa boshida turadi va pastga so\'nadi. "Maydon" — butun sahifa bo\'ylab takrorlanadi (fayl choksiz plita bo\'lishi shart).',
                        max_length=10,
                    ),
                ),
                (
                    "olcham",
                    models.PositiveSmallIntegerField(
                        default=220,
                        help_text='Faqat "Maydon" uchun: plita kengligi (px)',
                    ),
                ),
                (
                    "shaffoflik",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.16"),
                        help_text="0.00 dan 1.00 gacha. Fon matndan kuchli bo'lmasligi kerak — maydon uchun 0.12-0.20, tepa uchun 0.25-0.35 mos keladi.",
                        max_digits=3,
                    ),
                ),
                (
                    "izoh",
                    models.CharField(
                        blank=True,
                        help_text="Naqsh nimadan olingan — mato turi, joyi, sanasi. Mijozga ko'rinmaydi, lekin keyin manbani aniqlashda kerak bo'ladi.",
                        max_length=300,
                    ),
                ),
                (
                    "tartib",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Kichik raqam yuqorida turadi"
                    ),
                ),
                ("faol", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Naqsh",
                "verbose_name_plural": "Naqshlar",
                "ordering": ["tartib", "nomi"],
            },
        ),
        migrations.AlterField(
            model_name="shablon",
            name="kod",
            field=models.SlugField(
                help_text="Shablon fayl nomi, masalan: suzani", unique=True
            ),
        ),
        migrations.AddField(
            model_name="shablon",
            name="asosiy_naqsh",
            field=models.ForeignKey(
                blank=True,
                help_text="Shu dizayn uchun sukut bo'yicha fon naqshi. Mijozlarning ko'pchiligi fonni almashtirmaydi, shuning uchun bu yerda turgan naqsh eng ko'p ko'riladigan variant bo'ladi.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asosiy_shablonlar",
                to="taklif.naqsh",
            ),
        ),
        migrations.AddField(
            model_name="taklifnoma",
            name="naqsh",
            field=models.ForeignKey(
                blank=True,
                help_text="Fon naqshi. Bo'sh qoldirilsa — shablonning o'z asosiy naqshi ishlatiladi. Shu sababdan mavjud taklifnomalar o'zgarmaydi.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taklifnomalar",
                to="taklif.naqsh",
            ),
        ),
    ]
