# Generated by Django 5.0.14 on 2026-09-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0038_naqsh_qoshildi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taklifnoma",
            name="naqsh",
        ),
    ]
