# Generated by Django 5.0.14 on 2026-09-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0039_taklifnoma_naqsh_olib_tashlandi"),
    ]

    operations = [
        migrations.AddField(
            model_name="taklifnoma",
            name="mijoz_telefoni",
            field=models.CharField(
                blank=True,
                help_text="Buyurtmachining raqami — to'lovni tasdiqlash va mijoz taklifnomasini yo'qotib qo'yganda tiklash uchun. Mehmonlarga ko'rsatilmaydi.",
                max_length=20,
                verbose_name="Mijoz telefoni",
            ),
        ),
    ]
