# Generated by Django 5.0.14 on 2026-09-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taklif", "0040_taklifnoma_mijoz_telefoni"),
    ]

    operations = [
        migrations.AddField(
            model_name="saytsozlamalari",
            name="huquqiy_email",
            field=models.EmailField(
                blank=True,
                help_text="Shaxsga doir ma'lumotlarni o'chirish yoki o'zgartirish so'rovlari shu manzilga yuboriladi.",
                max_length=254,
                verbose_name="Huquqiy murojaatlar uchun e-pochta",
            ),
        ),
        migrations.AddField(
            model_name="saytsozlamalari",
            name="stir",
            field=models.CharField(
                blank=True,
                help_text="Soliq to'lovchining identifikatsiya raqami.",
                max_length=20,
                verbose_name="STIR (INN)",
            ),
        ),
        migrations.AddField(
            model_name="saytsozlamalari",
            name="tashkilot_nomi",
            field=models.CharField(
                blank=True,
                help_text="Ommaviy oferta kim nomidan tuzilayotgani — masalan \"Rahimov Shohzod Yakka tartibdagi tadbirkor\" yoki \"Oqqushlar MChJ\". Bo'sh bo'lsa, hujjatda rekvizitlar bo'limi ko'rsatilmaydi.",
                max_length=200,
                verbose_name="Tashkilot yoki YaTT nomi",
            ),
        ),
        migrations.AddField(
            model_name="saytsozlamalari",
            name="yuridik_manzil",
            field=models.CharField(
                blank=True,
                help_text="Viloyat, tuman, ko'cha va uy raqami.",
                max_length=300,
                verbose_name="Yuridik manzil",
            ),
        ),
        migrations.AddField(
            model_name="taklifnoma",
            name="shartlarga_rozi",
            field=models.BooleanField(
                default=False,
                help_text="Mijoz taklifnoma yaratayotganda shartlarga rozilik belgilaganmi. Eski (hujjatlar e'lon qilingunga qadar yaratilgan) taklifnomalarda bo'sh.",
                verbose_name="Oferta va maxfiylik siyosatiga rozilik",
            ),
        ),
    ]
