"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loyiha papkasidagi .env faylini o'qiydi (agar mavjud bo'lsa). Bu fayl
# git'ga hech qachon qo'shilmaydi (.gitignore'da) — maxfiy qiymatlar
# faqat shu yerda, mahalliy kompyuter yoki serverda saqlanadi.
load_dotenv(BASE_DIR / ".env")


def _env(nomi, standart=None):
    """Muhit o'zgaruvchisini o'qiydi.

    TAFTISH TOPILMASI (2026-09-14): oddiy `os.environ.get(nomi, standart)`
    faqat o'zgaruvchi .env faylida UMUMAN YO'Q bo'lgan holatda standart
    qiymatni qaytaradi — agar u BOR, lekin bo'sh qatorli bo'lsa (".env"da
    "NOM=" deb qoldirilsa), `os.environ.get` bo'sh qatorning o'zini
    qaytaradi, standart emas. Aynan shu sabab bilan DJANGO_ADMIN_MANZILI
    bo'sh qoldirilganda boshqaruv paneli butunlay ishlamay qolgan edi. Bu
    funksiya ikkala holatni ("yo'q" va "bor-lekin-bo'sh") bir xil — "qiymat
    berilmagan" — deb hisoblaydi, xatoning boshqa joylarda qaytarilishini
    oldini oladi.
    """
    qiymat = os.environ.get(nomi)
    if qiymat is None or qiymat.strip() == "":
        return standart
    return qiymat


def _env_bool(nomi, standart=False):
    """Muhit o'zgaruvchisini True/False'ga aylantiradi (masalan "1"/"true"/"yes")."""
    qiymat = _env(nomi)
    if qiymat is None:
        return standart
    return qiymat.strip().lower() in ("1", "true", "yes", "on")


def _env_list(nomi, standart=None):
    """Vergul bilan ajratilgan muhit o'zgaruvchisini ro'yxatga aylantiradi."""
    qiymat = os.environ.get(nomi)
    if not qiymat:
        return standart or []
    return [b.strip() for b in qiymat.split(",") if b.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Haqiqiy qiymat .env faylida DJANGO_SECRET_KEY sifatida beriladi (README'ga qarang).
# Bu yerdagi standart qiymat FAQAT lokal sinov uchun — production'da hech qachon
# ishlatilmasligi kerak (DEBUG=False bo'lganda quyida majburiy tekshiriladi).
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    "django-insecure-faqat-lokal-test-uchun-buni-almashtiring",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
if DEBUG and not ALLOWED_HOSTS:
    # Lokal development uchun qulaylik — production'da .env orqali aniq
    # domenlar/IP ko'rsatilishi shart.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if not DEBUG and not ALLOWED_HOSTS:
    # Taftish topilmasi: bo'sh ALLOWED_HOSTS bilan production'da Django
    # BARCHA so'rovlarni "DisallowedHost" bilan rad etadi — bu xato faqat
    # jonli 500-loglarda ko'rinardi. Sabab darhol, ishga tushish
    # bosqichidayoq aniq bo'lishi uchun ochiq tekshiruv qo'shildi.
    raise RuntimeError(
        "DJANGO_DEBUG=False bo'lganda .env faylida DJANGO_ALLOWED_HOSTS "
        "aniq ko'rsatilishi shart (masalan 'oqqushlar.uz,www.oqqushlar.uz') "
        "— bo'sh qoldirilsa, sayt HAR BIR so'rovni rad etadi."
    )

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Admin panelning manzili (standart "admin/" o'rniga) — .env faylida
# DJANGO_ADMIN_MANZILI orqali o'zgartirish mumkin. Standart "/admin/" juda
# ko'p botlar avtomatik sinaydigan manzil bo'lgani uchun, taxmin qilish
# qiyinroq bo'lgan o'ziga xos manzilga ko'chirilgan (config/urls.py'ga qarang).
ADMIN_URL_YOLI = _env("DJANGO_ADMIN_MANZILI", "boshqaruv-oqqushlar").strip("/") + "/"

if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise RuntimeError(
        "DJANGO_DEBUG=False bo'lganda .env faylida haqiqiy DJANGO_SECRET_KEY "
        "ko'rsatilishi shart (standart 'django-insecure-...' kaliti bilan "
        "production'da ishga tushirish xavfsiz emas)."
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Sitemap (sayt xaritasi) — qarang: taklif/sitemaps.py.
    # "django.contrib.sites" ATAYLAB o'rnatilmadi: usiz Django
    # so'rovning o'z hostini ishlatadi, ya'ni qo'shimcha jadval ham,
    # migratsiya ham, admin panelda yana bir bo'lim ham paydo bo'lmaydi.
    "django.contrib.sitemaps",
    "storages",
    # django-axes — admin panelga (yoki boshqa Django login sahifasiga)
    # noto'g'ri parol bilan bir necha marta urinilsa, o'sha IP/foydalanuvchini
    # vaqtincha bloklaydi (pastdagi AXES_* sozlamalariga qarang).
    # "axes" o'rniga o'zimizning taklif.apps.OqqushlarAxesConfig — bu faqat
    # boshqaruv panelidagi bo'lim nomini ("Axes") o'zbekcha qilib ko'rsatish
    # uchun (paketning o'zi bu nomni tarjima qilinadigan qilib belgilamagan).
    "taklif.apps.OqqushlarAxesConfig",
    "taklif",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise — statik fayllarni (CSS/JS/rasm) alohida serverga (nginx/CDN)
    # muhtoj bo'lmasdan, to'g'ridan-to'g'ri Django orqali tez va siqilgan
    # holda uzatadi. SecurityMiddleware'dan keyin, qolgan hammasidan oldin
    # turishi shart (WhiteNoise hujjatlariga ko'ra).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # LocaleMiddleware SessionMiddleware'dan keyin, CommonMiddleware'dan oldin
    # turishi shart (Django hujjatlariga ko'ra) — mehmon tanlagan tilni
    # sessiya/cookie orqali eslab qolib, har bir so'rovda shu tilni faollashtiradi.
    "django.middleware.locale.LocaleMiddleware",
    # Boshqaruv panelini xodim brauzer tilidan qat'i nazar doim o'zbek
    # tilida ko'rsatish uchun — LocaleMiddleware'dan keyin turishi shart
    # (aks holda LocaleMiddleware uning tanlovini qayta bosib ketadi).
    "taklif.middleware.AdminTiliniMajburlashMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # AxesMiddleware — django-axes hujjatlariga ko'ra MIDDLEWARE ro'yxatidagi
    # ENG OXIRGI element bo'lishi shart.
    "axes.middleware.AxesMiddleware",
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend — django-axes hujjatlariga ko'ra ro'yxatning ENG
    # BOSHIDA turishi shart (login urinishini u birinchi bo'lib tekshiradi).
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# --- django-axes: admin (va boshqa) login sahifasini brute-force'dan himoya ---
# Bitta IP+foydalanuvchi nomi juftligi ketma-ket AXES_FAILURE_LIMIT marta
# noto'g'ri parol kiritsa, AXES_COOLOFF_TIME soat davomida bloklanadi (shu
# vaqt o'tgach avtomatik ochiladi — abadiy qulflanib qolmaydi).
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # soat
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False

# Sayt ishonchli proksi (bizda — Cloudflare) ortida turadimi.
#
# Bu FAQAT HTTPS aniqlash uchun emas: taklif/chegara.py shu bayroqqa
# qarab X-Forwarded-For / CF-Connecting-IP sarlavhasiga ishonadi yoki
# ishonmaydi. Sarlavhani har kim o'zi yozib yuborishi mumkin, ya'ni
# proksisiz saytda unga ishonish chegarani chetlab o'tish yo'lini
# ochib qo'yardi.
ISHONCHLI_PROKSI = _env_bool("DJANGO_BEHIND_PROXY")


# --- Kesh ---
#
# IKKITA kesh bor va ular ataylab har xil:
#
# "default" — xotirada (locmem). Bu yerda sayt sozlamalari kabi arzon,
#   tez-tez o'qiladigan narsalar yotadi. Har bir gunicorn ishchisida
#   alohida nusxa bo'lgani muhim emas: eng yomoni — sozlama o'zgarganda
#   ba'zi ishchi uni bir necha soniya kech ko'radi.
#
# "chegara" — bazada. So'rovlar chegarasi (taklif/chegara.py) shu yerda
#   hisoblanadi va u BARCHA ishchilar uchun UMUMIY bo'lishi SHART. Agar
#   xotirada bo'lsa, har bir ishchining o'z hisobi bo'lardi va haqiqiy
#   chegara ishchilar soniga ko'payib ketardi — ya'ni himoya "ishlayotgandek
#   ko'rinib", aslida bir necha barobar bo'sh bo'lardi.
#
#   Redis o'rniga baza tanlandi: hajm juda kichik (bir necha yuz qator),
#   yangi xizmatni serverda saqlab turish esa ortiqcha yuk. Jadval bir
#   marta yaratiladi: manage.py createcachetable
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "oq-standart",
    },
    "chegara": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "oq_kesh",
        "TIMEOUT": 3600,
    },
}


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "taklif.context_processors.til_royxati",
                "taklif.context_processors.google_analytics",
                "taklif.context_processors.aloqa",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# .env (yoki hosting platformasi) da DATABASE_URL berilsa (masalan
# "postgres://foydalanuvchi:parol@host:5432/bazanomi"), shu haqiqiy
# ma'lumotlar bazasi ishlatiladi (production'da — Render, Railway va h.k.
# buni avtomatik beradi). Agar DATABASE_URL berilmagan bo'lsa (mahalliy
# kompyuterda ishlaganda odatiy holat), oddiy SQLite fayliga tushib qoladi —
# lokal ishlash uchun hech narsa sozlash shart emas.
#
# Taftish topilmasi: `dj_database_url.config(default=...)`ning o'zi ham
# ADMIN_URL_YOLI'dagi bilan bir xil xatoga ega — `.env`da "DATABASE_URL="
# (bo'sh) qoldirilsa, kutubxona buni "bo'sh qiymat berilgan" deb o'qib,
# standartga (SQLite'ga) TUSHMAYDI, aksincha bo'sh lug'at qaytaradi va sayt
# "ENGINE" xatosi bilan umuman ko'tarilmaydi — aynan `.env.example`
# tavsiya qilgan "bo'sh qoldiring" yo'lini buzadi. Shuning uchun qiymat
# avval o'zimiz (bo'sh-qiymatga chidamli `_env` bilan) o'qiladi.
_DATABASE_URL = _env("DATABASE_URL", f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
DATABASES = {
    "default": dj_database_url.parse(_DATABASE_URL, conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "uz"

# Taklifnoma ko'rish sahifasidagi til tugmasi shu ro'yxatdan tanlaydi.
# Mehmon interfeys elementlarini (yorliqlar, tugmalar) shu tillarda ko'radi;
# mijozning o'zi kiritgan matn/ismlar har doim asl tilida qoladi.
LANGUAGES = [
    ("uz", "O'zbekcha"),
    ("ru", "Русский"),
    ("en", "English"),
    ("tg", "Тоҷикӣ"),
    ("kk", "Қазақша"),
    ("ky", "Кыргызча"),
    ("tk", "Türkmençe"),
    ("kaa", "Qaraqalpaqsha"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

# Sana formati har bir til uchun alohida belgilanadi — sabablari va format
# belgilarining ma'nosi "config/formats/__init__.py" faylida tushuntirilgan.
# Qisqacha: shablonlarda `date:"DATE_FORMAT"` yozamiz, Django esa mehmon
# tanlagan tilga qarab shu papkadan to'g'ri formatni oladi.
FORMAT_MODULE_PATH = ["config.formats"]

# Testlar fayl yuklashni sinaydi. Standart holatda yuklangan fayl
# loyihaning o'z "media/" papkasiga tushib, o'sha yerda qolib ketardi
# (tasodifiy nomlar bilan: "n_HRrzR4g.jpg"). Bu ishga tushirgich test
# paytida MEDIA_ROOT'ni vaqtinchalik papkaga ko'chiradi — batafsil
# "config/test_runner.py" faylida.
TEST_RUNNER = "config.test_runner.OqqushlarTestRunner"

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# `manage.py collectstatic` shu papkaga yig'adi (production uchun; git'ga
# qo'shilmaydi — .gitignore'ga qarang).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (mijozlar yuklaydigan taklifnoma rasmlari, musiqa va h.k.)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Fayl saqlash (STORAGES) ---
# https://docs.djangoproject.com/en/5.0/ref/settings/#storages
#
# "staticfiles": WhiteNoise'ning siqilgan + hash-nomli (masalan
# "uslub.a3f8c1.css") versiyasi — brauzer keshini ishonchli boshqarish uchun.
#
# "default" (media — mijoz yuklagan fayllar): ODATIY holatda serverning
# o'zidagi jildga (MEDIA_ROOT) saqlanadi — bu FAQAT lokal development uchun
# yaxshi. Production'da (.env'da USE_S3=1 qilinganda) buning o'rniga S3-mos
# tashqi xotiraga (masalan Cloudflare R2) saqlanadi — MUHIM, chunki
# Render/Railway kabi platformalarda serverning ichki diski har deploy'da
# tozalanadi (ephemeral); mijozlar to'lab faollashtirgan taklifnomalarning
# rasmlari faqat shu tashqi xotirada saqlansa, doimiy (abadiy) qoladi.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

USE_S3 = _env_bool("USE_S3", False)
if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    # Cloudflare R2, Backblaze B2 kabi S3-mos xizmatlar uchun ularning o'z
    # manzili; haqiqiy Amazon S3 ishlatilsa bu bo'sh qoldiriladi.
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL") or None
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME") or None
    # Ixtiyoriy: agar fayllar CDN/maxsus domen orqali (masalan
    # "fayllar.oqqushlar.uz") uzatilsa, shu yerga yoziladi.
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN") or None
    AWS_DEFAULT_ACL = None  # bucket'ning o'z ruxsat sozlamalariga ishoniladi
    AWS_QUERYSTRING_AUTH = False  # media havolalar doimiy (imzosiz) bo'lsin
    AWS_S3_FILE_OVERWRITE = False  # bir xil nomli fayl eskisini bosib yozmasin

    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    elif AWS_S3_ENDPOINT_URL:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Self-service oqimida mijozga "to'lov qilish uchun bog'laning" deb ko'rsatiladigan
# Telegram kontakt. .env orqali haqiqiy admin username'ga almashtirish mumkin.
SAYT_ADMIN_TELEGRAM = os.environ.get("SAYT_ADMIN_TELEGRAM", "@taklifnoma365_admin")


# Sessiya muddati.
#
# TAFTISH. Django'ning standart muddati 2 hafta. Bu bizning ish oqimimizga
# umuman to'g'ri kelmasdi: mijoz "meniki" ekanini FAQAT sessiya cookie'si
# bilan isbotlaydi — "Mening taklifnomalarim" ro'yxati, mehmonlar qo'shish
# va statistika sahifasi shunga tayanadi. To'y esa odatda bir necha oy
# oldindan tayyorlanadi. Ya'ni mijoz taklifnomasini yaratib, ikki haftadan
# keyin qaytib kelsa, o'z taklifnomasini boshqara olmay qolardi.
#
# Bir yil — marosim tayyorgarligining tabiiy muddatidan uzunroq.
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365

# Har so'rovda muddat yangilanadi: saytga kirib turgan mijozning sessiyasi
# yil oxirida to'satdan tugab qolmaydi.
SESSION_SAVE_EVERY_REQUEST = True


# Production xavfsizlik sozlamalari
# https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# Bular faqat DEBUG=False bo'lganda (ya'ni haqiqiy serverda) yoqiladi —
# lokal development'da HTTPS bo'lmagani uchun ular runserver'ni buzadi.
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = int(_env("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Agar sayt nginx/caddy kabi teskari-proksi orqasida ishlasa va HTTPS'ni
    # proksi tugatsa (SSL termination), .env'da DJANGO_BEHIND_PROXY=1 qo'ying —
    # aks holda Django har doim so'rovni HTTP deb hisoblab, cheksiz redirect
    # tsikliga tushib qolishi mumkin.
    if _env_bool("DJANGO_BEHIND_PROXY"):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Xatolik-kuzatish (error monitoring): production'da kutilmagan 500-xatolik
# yuz berganda, Telegram bot orqali avtomatik xabar yuboradi (taftish
# bo'yicha qo'shildi — .env'da bu ikkalasi sozlanmasa, hech narsa yubormaydi).
# Bot @BotFather orqali yaratiladi, chat ID esa @userinfobot yoki botga
# yozilgan xabarni getUpdates orqali ko'rib olinadi.
# --- Zaxira nusxa (taftish bo'yicha qo'shildi) ---
# Baza nusxasi MEDIA BILAN BIR PAQIRDA turmasligi kerak: agar ilova
# ishlatadigan kalit zaxiralarni ham o'chira olsa, buzilgan yoki noto'g'ri
# ishlagan kod ikkalasini birdan yo'q qiladi. Kaliti ham alohida bo'lgani
# ma'qul — ZAXIRA_ACCESS_KEY_ID bo'sh qolsa media kaliti ishlatiladi.
ZAXIRA_BUCKET = os.environ.get("ZAXIRA_BUCKET", "")
ZAXIRA_PAROL = os.environ.get("ZAXIRA_PAROL", "")
ZAXIRA_ACCESS_KEY_ID = os.environ.get("ZAXIRA_ACCESS_KEY_ID", "")
ZAXIRA_SECRET_ACCESS_KEY = os.environ.get("ZAXIRA_SECRET_ACCESS_KEY", "")
ZAXIRA_ENDPOINT_URL = os.environ.get("ZAXIRA_ENDPOINT_URL", "")

TELEGRAM_XATOLIK_BOT_TOKEN = os.environ.get("TELEGRAM_XATOLIK_BOT_TOKEN", "")
TELEGRAM_XATOLIK_CHAT_ID = os.environ.get("TELEGRAM_XATOLIK_CHAT_ID", "")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "oddiy": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "konsol_xatolik": {
            "level": "ERROR",
            "class": "logging.StreamHandler",
            "formatter": "oddiy",
        },
        "telegram_xatolik": {
            "level": "ERROR",
            "class": "taklif.xatolik_xabarnomasi.TelegramXatolikHandler",
        },
    },
    "loggers": {
        # Django bu logerga har bir 500-server-xatolikni (va 4xx'larni
        # WARNING darajasida) yuboradi. Faqat ERROR (ya'ni haqiqiy 500)
        # darajasidagilar konsolga (server jurnaliga) va Telegram'ga boradi.
        "django.request": {
            "handlers": ["konsol_xatolik", "telegram_xatolik"],
            "level": "ERROR",
            "propagate": False,
        },
        # Kechasi taymer orqali ishlaydigan zaxira buyrug'i. Uni hech kim
        # ko'rib turmaydi, shuning uchun xatolik jimgina yo'qolmasligi
        # kerak — xuddi 500-xatolik kabi Telegram'ga boradi.
        "taklif.chegara": {
            "handlers": ["konsol_xatolik", "telegram_xatolik"],
            "level": "WARNING",
            "propagate": False,
        },
        "taklif.zaxira": {
            "handlers": ["konsol_xatolik", "telegram_xatolik"],
            "level": "ERROR",
            "propagate": False,
        },
        # TAFTISH TOPILMASI (2026-09-14): rasm.py'dagi "optimallashtir()"
        # funksiyasi buzuq/katta rasm uchun faqat shu logerga WARNING
        # yozardi — bu logerga hech qanday handler ulanmagani uchun
        # ogohlantirish amalda HECH QAYERGA ko'rinmasdi (na konsolga, na
        # Telegram'ga). Endi qolgan xato logerlar bilan bir xil tartibda
        # ulandi — mijozning rasmi rad etilsa, admin buni bilib qoladi.
        "taklif.rasm": {
            "handlers": ["konsol_xatolik", "telegram_xatolik"],
            "level": "WARNING",
            "propagate": False,
        },
        # TAFTISH TOPILMASI (2026-09-14): kunlik systemd taymer orqali,
        # hech kim ko'rmasdan ishlaydigan yana bir buyruq (zaxira.py
        # kabi) — bazadagi xatolik jimgina o'tib ketmasligi uchun.
        "taklif.eski_chiqindilarni_tozalash": {
            "handlers": ["konsol_xatolik", "telegram_xatolik"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
