"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loyiha papkasidagi .env faylini o'qiydi (agar mavjud bo'lsa). Bu fayl
# git'ga hech qachon qo'shilmaydi (.gitignore'da) — maxfiy qiymatlar
# faqat shu yerda, mahalliy kompyuter yoki serverda saqlanadi.
load_dotenv(BASE_DIR / ".env")


def _env_bool(nomi, standart=False):
    """Muhit o'zgaruvchisini True/False'ga aylantiradi (masalan "1"/"true"/"yes")."""
    qiymat = os.environ.get(nomi)
    if qiymat is None:
        return standart
    return qiymat.strip().lower() in ("1", "true", "yes", "on")


def _env_list(nomi, standart=None):
    """Vergul bilan ajratilgan muhit o'zgaruvchisini ro'yxatga aylantiradi."""
    qiymat = os.environ.get(nomi)
    if not qiymat:
        return standart or []
    return [b.strip() for b in qiymat.split(",") if b.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Haqiqiy qiymat .env faylida DJANGO_SECRET_KEY sifatida beriladi (README'ga qarang).
# Bu yerdagi standart qiymat FAQAT lokal sinov uchun — production'da hech qachon
# ishlatilmasligi kerak (DEBUG=False bo'lganda quyida majburiy tekshiriladi).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-faqat-lokal-test-uchun-buni-almashtiring",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
if DEBUG and not ALLOWED_HOSTS:
    # Lokal development uchun qulaylik — production'da .env orqali aniq
    # domenlar/IP ko'rsatilishi shart.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise RuntimeError(
        "DJANGO_DEBUG=False bo'lganda .env faylida haqiqiy DJANGO_SECRET_KEY "
        "ko'rsatilishi shart (standart 'django-insecure-...' kaliti bilan "
        "production'da ishga tushirish xavfsiz emas)."
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "taklif",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # LocaleMiddleware SessionMiddleware'dan keyin, CommonMiddleware'dan oldin
    # turishi shart (Django hujjatlariga ko'ra) — mehmon tanlagan tilni
    # sessiya/cookie orqali eslab qolib, har bir so'rovda shu tilni faollashtiradi.
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "taklif.context_processors.til_royxati",
                "taklif.context_processors.google_analytics",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "uz"

# Taklifnoma ko'rish sahifasidagi til tugmasi shu ro'yxatdan tanlaydi.
# Mehmon interfeys elementlarini (yorliqlar, tugmalar) shu tillarda ko'radi;
# mijozning o'zi kiritgan matn/ismlar har doim asl tilida qoladi.
LANGUAGES = [
    ("uz", "O'zbekcha"),
    ("ru", "Русский"),
    ("en", "English"),
    ("tg", "Тоҷикӣ"),
    ("kk", "Қазақша"),
    ("ky", "Кыргызча"),
    ("tk", "Türkmençe"),
    ("kaa", "Qaraqalpaqsha"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# `manage.py collectstatic` shu papkaga yig'adi (production uchun; git'ga
# qo'shilmaydi — .gitignore'ga qarang).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (foydalanuvchi yuklaydigan rasm/musiqa)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Self-service oqimida mijozga "to'lov qilish uchun bog'laning" deb ko'rsatiladigan
# Telegram kontakt. .env orqali haqiqiy admin username'ga almashtirish mumkin.
SAYT_ADMIN_TELEGRAM = os.environ.get("SAYT_ADMIN_TELEGRAM", "@taklifnoma365_admin")


# Production xavfsizlik sozlamalari
# https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# Bular faqat DEBUG=False bo'lganda (ya'ni haqiqiy serverda) yoqiladi —
# lokal development'da HTTPS bo'lmagani uchun ular runserver'ni buzadi.
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Agar sayt nginx/caddy kabi teskari-proksi orqasida ishlasa va HTTPS'ni
    # proksi tugatsa (SSL termination), .env'da DJANGO_BEHIND_PROXY=1 qo'ying —
    # aks holda Django har doim so'rovni HTTP deb hisoblab, cheksiz redirect
    # tsikliga tushib qolishi mumkin.
    if _env_bool("DJANGO_BEHIND_PROXY"):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
