"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Loyiha papkasidagi .env faylini o'qiydi (agar mavjud bo'lsa). Bu fayl
# git'ga hech qachon qo'shilmaydi (.gitignore'da) — maxfiy qiymatlar
# faqat shu yerda, mahalliy kompyuter yoki serverda saqlanadi.
load_dotenv(BASE_DIR / ".env")


def _env_bool(nomi, standart=False):
    """Muhit o'zgaruvchisini True/False'ga aylantiradi (masalan "1"/"true"/"yes")."""
    qiymat = os.environ.get(nomi)
    if qiymat is None:
        return standart
    return qiymat.strip().lower() in ("1", "true", "yes", "on")


def _env_list(nomi, standart=None):
    """Vergul bilan ajratilgan muhit o'zgaruvchisini ro'yxatga aylantiradi."""
    qiymat = os.environ.get(nomi)
    if not qiymat:
        return standart or []
    return [b.strip() for b in qiymat.split(",") if b.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Haqiqiy qiymat .env faylida DJANGO_SECRET_KEY sifatida beriladi (README'ga qarang).
# Bu yerdagi standart qiymat FAQAT lokal sinov uchun — production'da hech qachon
# ishlatilmasligi kerak (DEBUG=False bo'lganda quyida majburiy tekshiriladi).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-faqat-lokal-test-uchun-buni-almashtiring",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
if DEBUG and not ALLOWED_HOSTS:
    # Lokal development uchun qulaylik — production'da .env orqali aniq
    # domenlar/IP ko'rsatilishi shart.
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Admin panelning manzili (standart "admin/" o'rniga) — .env faylida
# DJANGO_ADMIN_MANZILI orqali o'zgartirish mumkin. Standart "/admin/" juda
# ko'p botlar avtomatik sinaydigan manzil bo'lgani uchun, taxmin qilish
# qiyinroq bo'lgan o'ziga xos manzilga ko'chirilgan (config/urls.py'ga qarang).
ADMIN_URL_YOLI = os.environ.get("DJANGO_ADMIN_MANZILI", "boshqaruv-oqqushlar").strip("/") + "/"

if not DEBUG and SECRET_KEY.startswith("django-insecure-"):
    raise RuntimeError(
        "DJANGO_DEBUG=False bo'lganda .env faylida haqiqiy DJANGO_SECRET_KEY "
        "ko'rsatilishi shart (standart 'django-insecure-...' kaliti bilan "
        "production'da ishga tushirish xavfsiz emas)."
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    # django-axes — admin panelga (yoki boshqa Django login sahifasiga)
    # noto'g'ri parol bilan bir necha marta urinilsa, o'sha IP/foydalanuvchini
    # vaqtincha bloklaydi (pastdagi AXES_* sozlamalariga qarang).
    # "axes" o'rniga o'zimizning taklif.apps.OqqushlarAxesConfig — bu faqat
    # boshqaruv panelidagi bo'lim nomini ("Axes") o'zbekcha qilib ko'rsatish
    # uchun (paketning o'zi bu nomni tarjima qilinadigan qilib belgilamagan).
    "taklif.apps.OqqushlarAxesConfig",
    "taklif",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # WhiteNoise — statik fayllarni (CSS/JS/rasm) alohida serverga (nginx/CDN)
    # muhtoj bo'lmasdan, to'g'ridan-to'g'ri Django orqali tez va siqilgan
    # holda uzatadi. SecurityMiddleware'dan keyin, qolgan hammasidan oldin
    # turishi shart (WhiteNoise hujjatlariga ko'ra).
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # LocaleMiddleware SessionMiddleware'dan keyin, CommonMiddleware'dan oldin
    # turishi shart (Django hujjatlariga ko'ra) — mehmon tanlagan tilni
    # sessiya/cookie orqali eslab qolib, har bir so'rovda shu tilni faollashtiradi.
    "django.middleware.locale.LocaleMiddleware",
    # Boshqaruv panelini xodim brauzer tilidan qat'i nazar doim o'zbek
    # tilida ko'rsatish uchun — LocaleMiddleware'dan keyin turishi shart
    # (aks holda LocaleMiddleware uning tanlovini qayta bosib ketadi).
    "taklif.middleware.AdminTiliniMajburlashMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # AxesMiddleware — django-axes hujjatlariga ko'ra MIDDLEWARE ro'yxatidagi
    # ENG OXIRGI element bo'lishi shart.
    "axes.middleware.AxesMiddleware",
]

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend — django-axes hujjatlariga ko'ra ro'yxatning ENG
    # BOSHIDA turishi shart (login urinishini u birinchi bo'lib tekshiradi).
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# --- django-axes: admin (va boshqa) login sahifasini brute-force'dan himoya ---
# Bitta IP+foydalanuvchi nomi juftligi ketma-ket AXES_FAILURE_LIMIT marta
# noto'g'ri parol kiritsa, AXES_COOLOFF_TIME soat davomida bloklanadi (shu
# vaqt o'tgach avtomatik ochiladi — abadiy qulflanib qolmaydi).
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # soat
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = False

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "taklif.context_processors.til_royxati",
                "taklif.context_processors.google_analytics",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# .env (yoki hosting platformasi) da DATABASE_URL berilsa (masalan
# "postgres://foydalanuvchi:parol@host:5432/bazanomi"), shu haqiqiy
# ma'lumotlar bazasi ishlatiladi (production'da — Render, Railway va h.k.
# buni avtomatik beradi). Agar DATABASE_URL berilmagan bo'lsa (mahalliy
# kompyuterda ishlaganda odatiy holat), oddiy SQLite fayliga tushib qoladi —
# lokal ishlash uchun hech narsa sozlash shart emas.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "uz"

# Taklifnoma ko'rish sahifasidagi til tugmasi shu ro'yxatdan tanlaydi.
# Mehmon interfeys elementlarini (yorliqlar, tugmalar) shu tillarda ko'radi;
# mijozning o'zi kiritgan matn/ismlar har doim asl tilida qoladi.
LANGUAGES = [
    ("uz", "O'zbekcha"),
    ("ru", "Русский"),
    ("en", "English"),
    ("tg", "Тоҷикӣ"),
    ("kk", "Қазақша"),
    ("ky", "Кыргызча"),
    ("tk", "Türkmençe"),
    ("kaa", "Qaraqalpaqsha"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# `manage.py collectstatic` shu papkaga yig'adi (production uchun; git'ga
# qo'shilmaydi — .gitignore'ga qarang).
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (mijozlar yuklaydigan taklifnoma rasmlari, musiqa va h.k.)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Fayl saqlash (STORAGES) ---
# https://docs.djangoproject.com/en/5.0/ref/settings/#storages
#
# "staticfiles": WhiteNoise'ning siqilgan + hash-nomli (masalan
# "uslub.a3f8c1.css") versiyasi — brauzer keshini ishonchli boshqarish uchun.
#
# "default" (media — mijoz yuklagan fayllar): ODATIY holatda serverning
# o'zidagi jildga (MEDIA_ROOT) saqlanadi — bu FAQAT lokal development uchun
# yaxshi. Production'da (.env'da USE_S3=1 qilinganda) buning o'rniga S3-mos
# tashqi xotiraga (masalan Cloudflare R2) saqlanadi — MUHIM, chunki
# Render/Railway kabi platformalarda serverning ichki diski har deploy'da
# tozalanadi (ephemeral); mijozlar to'lab faollashtirgan taklifnomalarning
# rasmlari faqat shu tashqi xotirada saqlansa, doimiy (abadiy) qoladi.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

USE_S3 = _env_bool("USE_S3", False)
if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    # Cloudflare R2, Backblaze B2 kabi S3-mos xizmatlar uchun ularning o'z
    # manzili; haqiqiy Amazon S3 ishlatilsa bu bo'sh qoldiriladi.
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL") or None
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME") or None
    # Ixtiyoriy: agar fayllar CDN/maxsus domen orqali (masalan
    # "fayllar.oqqushlar.uz") uzatilsa, shu yerga yoziladi.
    AWS_S3_CUSTOM_DOMAIN = os.environ.get("AWS_S3_CUSTOM_DOMAIN") or None
    AWS_DEFAULT_ACL = None  # bucket'ning o'z ruxsat sozlamalariga ishoniladi
    AWS_QUERYSTRING_AUTH = False  # media havolalar doimiy (imzosiz) bo'lsin
    AWS_S3_FILE_OVERWRITE = False  # bir xil nomli fayl eskisini bosib yozmasin

    STORAGES["default"] = {"BACKEND": "storages.backends.s3.S3Storage"}

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    elif AWS_S3_ENDPOINT_URL:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL.rstrip('/')}/{AWS_STORAGE_BUCKET_NAME}/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Self-service oqimida mijozga "to'lov qilish uchun bog'laning" deb ko'rsatiladigan
# Telegram kontakt. .env orqali haqiqiy admin username'ga almashtirish mumkin.
SAYT_ADMIN_TELEGRAM = os.environ.get("SAYT_ADMIN_TELEGRAM", "@taklifnoma365_admin")


# Production xavfsizlik sozlamalari
# https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
# Bular faqat DEBUG=False bo'lganda (ya'ni haqiqiy serverda) yoqiladi —
# lokal development'da HTTPS bo'lmagani uchun ular runserver'ni buzadi.
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Agar sayt nginx/caddy kabi teskari-proksi orqasida ishlasa va HTTPS'ni
    # proksi tugatsa (SSL termination), .env'da DJANGO_BEHIND_PROXY=1 qo'ying —
    # aks holda Django har doim so'rovni HTTP deb hisoblab, cheksiz redirect
    # tsikliga tushib qolishi mumkin.
    if _env_bool("DJANGO_BEHIND_PROXY"):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Xatolik-kuzatish (error monitoring): production'da kutilmagan 500-xatolik
# yuz berganda, Telegram bot orqali avtomatik xabar yuboradi (taftish
# bo'yicha qo'shildi — .env'da bu ikkalasi sozlanmasa, hech narsa yubormaydi).
# Bot @BotFather orqali yaratiladi, chat ID esa @userinfobot yoki botga
# yozilgan xabarni getUpdates orqali ko'rib olinadi.
TELEGRAM_XATOLIK_BOT_TOKEN = os.environ.get("TELEGRAM_XATOLIK_BOT_TOKEN", "")
TELEGRAM_XATOLIK_CHAT_ID = os.environ.get("TELEGRAM_XATOLIK_CHAT_ID", "")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "oddiy": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "konsol_xatolik": {
            "level": "ERROR",
            "class": "logging.StreamHandler",
            "formatter": "oddiy",
        },
        "telegram_xatolik": {
            "level": "ERROR",
            "class": "taklif.xatolik_xabarnomasi.TelegramXatolikHandler",
        },
    },
    "loggers": {
        # Django bu logerga har bir 500-server-xatolikni (va 4xx'larni
        # WARNING darajasida) yuboradi. Faqat ERROR (ya'ni haqiqiy 500)
        # darajasidagilar konsolga (server jurnaliga) va Telegram'ga boradi.
        "django.request": {
            "handlers": ["konsol_xatolik", "telegram_xatolik"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
